---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vault-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/vault/operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-vault-operator-plans
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: cluster-apps-vault-operator
#   path: ./kubernetes/apps/vault/vault-operator/plans
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   wait: false # no flux ks dependents
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
