kind: ENC[AES256_GCM,data:sjh51c1f,iv:7OwjECwDYQcUz9TxSw++7X/5In6J2AIWew+9zjiJHHM=,tag:1BtXEsZG6FRMSzdHZEI/NA==,type:str]
ansible_user: ENC[AES256_GCM,data:F18kGjP0Kg==,iv:A0YX4GKe/uUW1jtYQLZzNHtmyIckm5YE9DcXW+L3Las=,tag:6lrdDtS/jfYF8e5YTbaafw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WCavVh3krGXBYNKK,iv:DsETGIKqALX2WAGw9X9J895IqM/MLpsZKrIQyMKaLys=,tag:jDSJ23aJBRx+y0ZvdEUxdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqdzyqewl8pjzr2fmq66xznef6apcdvkm6lk5j0qzllvwul4ryuqnv2rgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSzJVdTdaV0RldHpyUkEz
            TzY2b2ZuZFFRQXFveWY5RE11VWtNbE5jTDJjCnZESndEYWdCVzV6eHQ4MGk5UUUx
            TGpFZnVEeUZDaGU5TWZSSG9XQlQxc3MKLS0tIFhpT1luTWpyaDFtOHdjNjdwM0o4
            c2liY29RdVYxM2U1NVdaMlF4ZHBqYmsKNLz/3lXNTS1hL/SOM58VsxEIaxNSfmsG
            MpvxYouvKn8LHdSSfNrY5LYqIPUMHtU65vq9zrVNM1dIkRMCCTakxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T04:56:28Z"
    mac: ENC[AES256_GCM,data:I8+HRFS2V50TLPZnWMshqaEvwqjI6zPzCN+pxZlQlAnTIS4V9YVR4c6pJ8Ef42lGlkfi/AZ8z9qPYt8PfAk6BTE1PXJV7g6u6WhX73nmeE7YAPV5+sRqA5m26SqfLafcLJMAh5Lo87MetyXMLFp1i6mDrVxbSFzKkvn8UolPHyw=,iv:8p9vU11H7PN1bzBUPGUDh+9l34woKJqOPXIULZrTl44=,tag:TdDl8YGTnTGacND+VUXpVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
