kind: ENC[AES256_GCM,data:5goNtZ1j,iv:UwsQb0p5R4qGi/jkJUPMufWsviGuEcH/lM6TkW7MJkc=,tag:NYr+Qn6rWf6R2YYwjtnuUQ==,type:str]
ansible_user: ENC[AES256_GCM,data:N8cWNOw9aQ==,iv:ukRDRkRz+3+MANjGbZeB6fBVd47OKC9Ttu/9Lf/bK4A=,tag:cq7Dq1H6WTefQnwplQpefQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:hkkqrmUwxhUUzNOg,iv:wcR11GKpjs5GgfR/fSyamUDLi1dascvfXO9XMb35Sxs=,tag:sx8dLu2e1WcRDsWPIUXm6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqdzyqewl8pjzr2fmq66xznef6apcdvkm6lk5j0qzllvwul4ryuqnv2rgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOWFJSFFCb1F5SkdPL0Rv
            Y3R4bEluNW84MnRYcXA4L3hDSVNoZzVOclI0CnZhcEhFWTh5QkFCNzhSSXIxOFdD
            T0JCZ0JyQ0ZzYVNuNVZDaDBPa2EvVE0KLS0tIFNZWnEyajFIME9saS9WYk0wdGtJ
            TVdFNGtSTUIzWHhhUDF4TnFXRDkvK1EKGgFxjwGuk2PXUJQV5MqPS9zWLBqsFQyw
            PD2f8NVG+ZWpRy/XM5P0AlxXeGn2DFecSyrVVR3SvbK2Yg4WCwJRTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T14:58:05Z"
    mac: ENC[AES256_GCM,data:uz+mNxhT0gEMZ54UNC+y7T4lqqNOpaCijT1nxPq88JRudpnUs9OdmTrA9uiwhznBYmfjCCEjdNcY7pBsc6jenZ0HE3qJsqI/GQdz5r9NFUQDPTKMdOHr4h/A/T6jsFOITU0QT4b8pzrqXkPh/S3k8eFLDDNuMWfgvzJVJjocp4E=,iv:azESXKFmcgW/h2TqZ/NeyO50Yxq1cJeG41y0pba6HNI=,tag:lYWAJhJ7qw6TIJMID39dnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
