apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:BfMZ5Y/zr42mCTtjWx0ZQI9GWsWrJJHT,iv:NDgouv2sfHXhJybvDpj6BTWOjs8uRgYIOflX82zwqaQ=,tag:N/v4TvX21cc9T3G4rS+Ffw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqdzyqewl8pjzr2fmq66xznef6apcdvkm6lk5j0qzllvwul4ryuqnv2rgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY3Z3R1R3cWNnUWtYWUpR
            eklFbUd3b3NOZnhBMHVyOFpiMXZMWEdZa1ZrCnNybUF0Y2p2Tjk2OGJsUHpLY21U
            TWhOVVRVOFNaWTNocVgzcjlRWXVwbGsKLS0tIFF4RGRFWEQ5MnFrakpKSWhhc0dT
            L2FkK1Vka1BKTmFISUZNR3JLcHF5S1EKbOpESMQeLSc3gcWR8luKe3uOYCgpxA8j
            rVDf2d+ASYyeQ6IfoiC7v4UvarzWp6QshY/69Ri5YhRX0dMV88v0wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T14:58:05Z"
    mac: ENC[AES256_GCM,data:+j7KJ9HDPXkHP3Vfr7ej6MkA+VbJXn+ce69Xg0YQfVQYd8lDqupKdmoMAIt1onXcli+Kee5cSy1Dt+9aOjXREzpBW3PaByaTnPTErqJsAwDqPy3LSjZBTZeWmBa4nRR8nA67j5g+Amm5QmuwkoPNN7I7nGsEWWbU/xWmavAP+pw=,iv:yGP/ouxGAzy+Bt27yq5wF+V5lce5LhiLblRnYqwNXRE=,tag:b2xOJqmEOfa37e87HuEJvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
