apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:cLnhypMWqU+82HluHHGa1caC/S0E/VV78w9vnyuFdlbQn3dQaBsGWA==,iv:iqlFUPUuvvTgBzUJOICqDh1uMP3cuoo4JG+6c1hJuxA=,tag:fS19pkj5g5KCvw1h+lUFRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqdzyqewl8pjzr2fmq66xznef6apcdvkm6lk5j0qzllvwul4ryuqnv2rgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaGYzZ0FxTnRYYzFNeGpN
            QXFqT3JDc3ZsOTJEQlpDTDhGeHlSWVZjYTBNCjRadFZvUCt1N1hCelZYZDg4dXhs
            bGFtYURwQm11Q1E0R1pQNGVJNkloY1kKLS0tIHBXUTR1Mi9yYzlVdVJQN0gzcWV3
            aTBUdW9QYUdXd0xpN0VtZHc4bmJ4WTAKOuKUypRRhg4AxcxO4S9baPfsexx2H/oW
            IX8vuFlgNWqfdss5376m/miQ9K9rpFikScqWJ0So5Qn786cY+mg1qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T14:58:05Z"
    mac: ENC[AES256_GCM,data:Rq7mQQTJOag+vhuheJtSFpOGddvIasLfj/z1RQyfnIeYT3ZdWhlSWZ1WO+/vJtNptHIVNVRMN3yS5BPKDcjLWxBa1muNw986Ot/bR/f7xRDLtCQTDJnQp58fqh+f//a6MexDAPrlXP4QLYc7g+2HnWpKvCVs4xUtmQTPmufBtm4=,iv:eXSduNQJIq+wSYHE/ADCSH8ropQsNNMWZKCey79ByF4=,tag:ZX2D0ojLUYLItmWjJeqoUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
