apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:D2bh7Qs=,iv:Dn8k4KDKP9t6ThrklouXeZeGpTwN84o3A8cjD00Sx8o=,tag:UbWaOIT3n5krj8jAgFfcFQ==,type:str]
    password: ENC[AES256_GCM,data:rrwbZaSkG7BnUfZScKk5Yaag5OCYWXfaRAyhDHCNsNuUJ5ulMcCaTun57hGyGoz0yeQnHnbgbStTsSza,iv:1UKRhYv1ZuJU/3JWkMmLwuugFWDbRdhaGo4buwGramw=,tag:QDGXoyNizhsidchyCLU6rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqdzyqewl8pjzr2fmq66xznef6apcdvkm6lk5j0qzllvwul4ryuqnv2rgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRDFrZ0tXMEpXLytwYmVW
            czZQKzc3TDRab29RZ1FsWkpNWHVNMmtRR2kwCkwwZm5LTyttQjB3akZhMnRtLzV2
            aE81MWErOCtLV2hsckROMzFQS2hQSlUKLS0tIHAzSjVrMGdiUGE3ZTR4SW5YcEdS
            SjIvUjkvb2Jvamh0cHRnNmJXTWF6cWsKR9x2YOSQXS2QAcGXsAuu4/X/fhq0JQIx
            Md3uukMbuNNRxI1ggef8nYMf40JmvdYdJc2Eza7MxbO6pwhYQYwZqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T04:56:29Z"
    mac: ENC[AES256_GCM,data:JotWcNOIH2r4O4llFAvzlq8fSpXusgXOTDI5SJjdYpEQz4hup7rtuPRvCEjK0Y2oz9AOHW/Uzjvhq4KrF7YR8R568kTaqgpoW8WAIUXUABjvf97x5lbhMTEr4/bIOXPvd8zGZTPYKZITngCoC69b+i4dcEYvQt7RSZzqzMzXyzY=,iv:SzpDlVSAn0wBFAG7h3kuTeyecfvSTWc6bLoB5fll4U0=,tag:Zy3mYxspATBw/mYvODdMmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
