apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8+TdxOY=,iv:uhFa0UN4S5tMcRu229C3VMI8bTzR4ssl9vD76cdwdQw=,tag:N6jjJPibRQCAiM3NIlDVrg==,type:str]
    password: ENC[AES256_GCM,data:20dHJmPq1Sh7WKwv+fVnC3LZX1mQdrY5q6lAvxXIyJ+98Id1E73XNHlCvdhEBZfLl9w27/+OqbI9eQpm,iv:i5Pg3mJly0fEw5JK/7yz6yA0WTkCmvoOJ7EyMe/lQfA=,tag:Bh0sVUXMNBtFoX1509nE8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqdzyqewl8pjzr2fmq66xznef6apcdvkm6lk5j0qzllvwul4ryuqnv2rgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeGhNWU9GZUpHVTR6aFBy
            eHh4YStSc05lSVZwT3dtdlFCOWdnMDZWRjJrClJpamk3V0dxTjRKVnFCalE1QTQ0
            bitBL2NGM3h6bHV1U0k3VnNBWCs4MDgKLS0tIExxUUpMWUdJc2hhK21wUFdWSDU1
            dkp1cFB2ajZNUlBSME1sd0h5UlZvcVUKITj+KmRt4aCIokZ7QnHSwN4Ce4uY1LHH
            e/CD0xvcffUmKEQ0PmEiARBqixjij2mtZBtZfVD6GIx/lrmk2mAg4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-03T00:27:15Z"
    mac: ENC[AES256_GCM,data:mMtqpavojHi8IPVMlGTpQC8uWZZI17lwVB0vEx2Db4qANztI8vLFUA/82AjYl5sJG4jioGbDXDlSt8r7pRDymyO+QAdf9B9tdtThEw6np00oh6F0n2lEr5qRFpr85yKYVzsnbRigdBCF4IoYPEr9PfOfOGwSz0JjHdjY1i//bdA=,iv:xXw/CmtVaTTa8rwugiCbPbYOniK8H6kPIGczA5es434=,tag:96k0S16Vu8Al/71mT2PSdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
