---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault-operator
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
    - name: ingress-nginx
      namespace: networking
  values: {}
