---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: vault-operator
      version: 47.0.0
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn: []
  values: {}
