---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  METALLB_LB_RANGE: "192.168.1.40-192.168.1.50"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.40"
  METALLB_INGRESS_ADDR: "192.168.1.41"
  KUBE_VIP_ADDR: "192.168.1.65"
  COREDNS_ADDR: "192.168.1.42"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  VAULT_STORAGE_FILE: /vault/file
