apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:76WLKcA6kXSluRE=,iv:SaDOCGSbyQea62k/4im5/EUFkAITovMz0Z913rfTCHI=,tag:JCwcs8q0fhJxENZRPlczSA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GOIrp/y2wxZ2CAkSGWUAL7w=,iv:ftpJWPQ0UL2deq/EWbadybWzEm6SPEPzLElN8ZicNNo=,tag:al20gUTTCcynNrxgaUIMCg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NHhYnbEPzmdMlj/F6tEA0LKequexX8i+kifZjnX9ehQ7Ju6P,iv:D8jOakMwJikO3pcMe5dcEgXZYvD2t6MBBCxtOp5mzXc=,tag:7xjb+9iWzTHjDX//KF2QhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqdzyqewl8pjzr2fmq66xznef6apcdvkm6lk5j0qzllvwul4ryuqnv2rgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dG1kcDE5MVExd2FOODlI
            cFZnR0Q4TWxTeDdjcUh0SEhGYUJwOEUwUFJrCjkvV09WdmNaWVRqOXJ4TklMUU9W
            MXYyTm9UWTdUM3RGbTQ1VkJyUXZsblEKLS0tIGF0UU41dzdlY2VyWEl2ZkFTdHBo
            b3ZIMTRWVHpLbDRUdllqVytWakpSaFUKg0nqQAtU/Fu8+Hn7+GJ7MtBA0ZE2wf0/
            s1DLpVpzQCeSjZZ8jP51rW2ge4MDoNUclJ2I/x1Ac60Yp5SOlsdIxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-03T00:27:12Z"
    mac: ENC[AES256_GCM,data:+KLkXwquAmqaq7b6kjtB3BM2hQEQ0f5cgLZd0IMlBsPXvAsG36Md11Sep/sdpDvV3lZP8pKda1STr1C+q9OHZnzoZAxIB1vxsRmc6te6dOScTvr1nyjk42j617B5DciY/dfdrmTfq64IWWrKOGyosSaAbalqDoCvaNefQHOE898=,iv:9rEoZLvGJDn8mmySWsdXBpoi091MXW4AH5AQPYz9ljY=,tag:8qLV+OJHy0DFHu/8+gD1wg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
