apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:A1U7YBS1zxa9VSGcWArf7CjKumeN//4tywmH5xKzshHkEy73,iv:bvwpfboe4Gzu7ODMwhFg7pPr+cwntExc7Sv6tsUlKLQ=,tag:1M18PcqLmuTyhX9cmU1REQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:H3dwLbTZjgyOLZkCz3ASzdFeuedulJBUSNhJaZSx9X2ZSBiFe7TzMCEUqV3Q8wX29WP9BsmMYnJonTCDfzBDWDL/Zo6WNYfSE6h07VbNpex5He9+w0MDFjGzIa01gphQ37aySKoMHn/bDRs5jLzOWo9tqv3DCRKQXAKCfBobn+lF1SOG5YlJHVobvPU6p0ntpuFG5fvqltqECb0S12XvCWrOgZ5cRSIkgKZ7MNgszw==,iv:N1zQRDQ4HUy/SibrYdDB2qTGXpksTNdLqOf8xUxxfck=,tag:lsusYjm2zXneYORnPC5fVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqdzyqewl8pjzr2fmq66xznef6apcdvkm6lk5j0qzllvwul4ryuqnv2rgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MndkczJmT2Uvd1dWckZH
            RnZDaEhvcVZucFVUUHkvNjJzVzBVclNaWkJVClVkWkttWFREZWdMcFh3T0VWdjRw
            Q2Vqek1rU0JONlBLbWdBZDlXZm5ySTQKLS0tIGtrVkN4R2VlbmpPRDV6Tjg5SHVn
            YWJBUVdNRWI2L01Dc2IxaUs2YThBeVkK3PszABSoefGLZ7ziiG0evKr/BIPbLgi2
            xVb7LatsIxj4scwPe+1eldOGWaTz7884jTRct6HcMi5gS7Mmykj7/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T17:10:54Z"
    mac: ENC[AES256_GCM,data:9snFFOdow5vk4eFLDIvYnioaM4quD8zL9ls6JkylUxb5XPfb9silNcN+IjbCrpa7pz+h7sF44n3Olod93G+WvLPLJASE6PdphztcC3a0BnWd63zhBMLe8p2/XIv6UbUGwe9DdOmQj4DHsGRBanGJ7fD8ZHp+cR5QpGLZWvLj18U=,iv:CjEntYjM6Rdora5W5wUMITJTqbzu/GAhs5xbHNReKoY=,tag:Bcf0R2x5oQBSMhChPXFByg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
