apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:8D2tDwgZ57V8M7oBbao61Auk8MxpE9smCdZPWnkzAm5JB/cB,iv:6uI3KIqAs7x5iL+4Rvt4+QtDH7AHWk5shPycMtbbM6k=,tag:oJrcr8eSntdEM+YxeuBMYQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:hCgdWJm6yM7vMW2z2wcPJbsRMed8i8VgR8GSwYFcFH6u+7GNRvoCKV2hLfMMlLWitKGas+qRMyn52qpv7YvwVslK8BQS1zaA5XMWOEmdJiXfr3Ql2mFqnTRuehebyOE9vT67bXnDd5hHotX411LqBYKiynMo18XP8Htv7uLKx4DfP8Hfs5xdTs8m9OXyRFLJX8vrHMUIq9upkQ2vNy5hohGQJs1JrjQkwdMMMEVO6g==,iv:zJI3F+PATq3lHZ7R+IMbIbLXv27mh5M1w40nwbwK8l4=,tag:vW9EwfS+RNLP6mrYowrlqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqdzyqewl8pjzr2fmq66xznef6apcdvkm6lk5j0qzllvwul4ryuqnv2rgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTnpEdG1ITGlxWnVNMWNE
            UU1CcW80Sk1DNHZyam01NEVLZ1FoMll3NFNJCldvL3lKZjIzM1hIeWthYjNGRUlj
            eDJCNEVMZkdhZXdmY2RLQi9KcDlqNlUKLS0tIGRXWkQ2aXBlU2x2dEk4NUVCeXVO
            aldGMTcwc1M3Q0owZkg1NTRrYXIwZEEKfkSXhTAa0RQP8eLGyIYZH85rxMuQu727
            yYPWAsmb7LC59OgfwJFuv5Z8UzaYJvUqpKj8olSpUsOSBW0NEQlYiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T14:58:05Z"
    mac: ENC[AES256_GCM,data:+kfkW8o4GgPFXRm+izPzPuS/jVaW8VEK2LZ+SSW8Y2eG6+irk6IeFX8ydngz6HQzZs5q83LjmQGjlP5hgG47kdQm6jnNzy9bzfFA4VgFCV5mVZjwp33JyZVr3GjNogAIizA0GU0ipU2Pjfk2aNgiNyA03I5f9xQ23PpEya30THE=,iv:qvFozmRtThdx3ydmqrHKCuWDZFgUXAxWjajkL+OAvCQ=,tag:HnYsBWk52ydqLplysnPSqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
